### PR TITLE
CSS: add support for 'line-break' and 'word-break', and other fixes

### LINKED ISSUE #362: Unsetting font for a class
I have a book that uses an embedded font for small caps, like this:

```
@font-face {
  font-family: "KpRoman";
  src: url(../fonts/KpRomanSC-Regular.otf);
}
span.smallcaps {
  font-family: "KpRoman";
}
```

I'd like to create a user style tweak to disable the embedded font and use whatever default text font I choose, and its native small caps (if available). I don't want to disable embedded fonts completely, just for this case. I was successful with:

```
span.smallcaps {
  font-family: "none" !important;
  font-variant: small-caps;
}
```

But here are some questions:

1. Why do I need `!important`? Shouldn't a user style override book styles?
2. Why didn't `inherit` work instead of `"none"` (a non-existing font)?
3. Is there a better alternative way?

### LINKED ISSUE #420: CSS: adding support for "line-break:" and "word-break:"
Regarding https://www.mobileread.com/forums/showthread.php?t=337181

> (@Frenzie) Actually there is `line-break: anywhere`, which while not currently supported is presumably fairly easy to implement should someone wish to do so.

https://developer.mozilla.org/en-US/docs/Web/CSS/line-break

Just forcing, after libunibreak has set flags, always: `m_flags[pos-1] |= LCHAR_ALLOW_WRAP_AFTER` would give:
<kbd>image</kbd>

It would need some added css parsing simple code and slots, and would waste 1 bit in a lUInt32 flags (so, nearly filling it, we might need to bump it to lUInt64 soon to store more flags - @NiLuJe : could that cause some performance issues on 32bits arches, doing some bitwise `&` checks ? Or is it negligeable ?).

But I must say it's really ugly and unreadable.
I know it's just a CSS property that it might be nice to support, and users could get things however ugly they want via style tweaks... But isn't it our mission statement to get only nice rendering ? :)

### PR DESCRIPTION
**Pull request by poire-z**
#### LVXMLParser::ReadText(): fix parsing at buffer boundaries

Avoid '`</sc`' at buffer end to miss matching '`</script>`' if it would come next when reading from file stream.
A bit of clean up of this part of the code, added comments as I understand what bits are supposed to do.
A bit risky though - spent hours on this, but not 100% sure I didn't break anything.
See https://github.com/koreader/crengine/pull/405#issuecomment-781570875 and follow ups.

#### TextLang: fix lang_tag first part comparison

"en" and "en-US" do start with "en", but "eno" should not.

#### CSS font-family: fix parsing of 'inherit' and '!important'

Proper parsing of "!important" at end of font-family.  Also try to handle "inherit" in the most compatible way, even if not per current specs: "inherit" is nowadays invalid when not standalone.
We have seen books with '`font-family: "Some Font", inherit`', that Calibre 3.x would render with "Some Font", while Firefox and Calibre 5.x would consider the whole declaration invalid.
So, best to just ignore any non-standalone "inherit", and keep parsing the font names.
See https://github.com/koreader/crengine/issues/362#issuecomment-778697971 and follow-ups.
Closes #362. Will allow closing https://github.com/koreader/koreader/issues/6886.

#### CSS: support a few -epub-* and -webkit-* properties

Mentionned in early specs of EPUB3 (and later deprecated), or only supported as -webkit- at some point in the past, so these can be found in some books without the newer alternatives.
See https://github.com/koreader/crengine/issues/420#issuecomment-779417965 and follow-ups.

#### Text fragment flags: add LTEXT_HAS_EXTRA

Replace LTEXT_HIDDEN and have "visibility: hidden" use it.
This might allow adding support for rare CSS text properties (like "visibility", "line-break) without wasting a bit in the LTEXT_ flags.
Have any generated content (list item markes, pseudo elements, BiDi markers) pass their originated node to AddSourceLine() so we always have access to the node to fetch these extra properties.

#### CSS: add support for 'line-break' and 'word-break'

See comment in the code for how/why we do it a bit differently than other implementations, with possibly not the same results (in hopefully only edge cases).
See https://github.com/koreader/crengine/issues/420#issuecomment-780547104 and around.
Closes #420.

Firefox (top) / KOReader (bottom):

<kbd>image</kbd>

<kbd>image</kbd>

Same with smaller width, which should exhibit some differences
<kbd>image</kbd>
For the CJK stuff, we differ on auto - which is ok per-specs :) but are similar on others, so we must do that loose/normal/strict stuff quite alright.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/crengine/423)

### CODE REVIEW

File: crengine/src/textlang.cpp [hunk 1]
```diff
@@ -11,14 +11,36 @@
 // Uncomment to see which lang_tags are seen and lang_cfg created
 // #define DEBUG_LANG_USAGE
 
+// Check a lang tag (or its first part) against a lang (without subparts)
+static bool langStartsWith(const lString32 lang_tag, const char * prefix) {
+    if (!prefix || !prefix[0])
+        return true;
+    int prefix_len = 0;
+    for (const char * p=prefix; *p; p++)
+        prefix_len++;
```
Comment (NiLuJe) [inline crengine/src/textlang.cpp:24]: That's `size_t prefix_len = strlen(prefix);` ;).

Comment (poire-z) [reply crengine/src/textlang.cpp:24]: Oh :) Might not have been the best thing to learn C with crengine :)
Strangely, there are only 4 occurences of strlen() in the codebase, all added only in 2015 by its original author.

Comment (NiLuJe) [reply crengine/src/textlang.cpp:24]: Well, it's not usually used as much in C++ because you're rarely using actual C strings unless you need to work with C APIs ;).

**Comment by poire-z** [comment]
Got a book in French that abuses `&nbsp;`, between words like "la&nbsp;maison" or "pour&nbsp;arriver", which causes some lines to have wide word spacing.
None of the properties added in this PR seem to help :/ Any idea on how to allow a break on such `&nbsp;` ? Or other CSS properties that could help with that if we were supporting them ?
Or is `&nbsp;` pure content and there's nothing CSS is allowed to do on it?

**Comment by Frenzie** [comment]
You could always consider adding a custom property I suppose. Something in between `loose` and `anywhere`.

Incidentally, there's also https://www.princexml.com/doc/css-props/#prop-prince-linebreak-magic

**Comment by poire-z** [comment]
> You could always consider adding a custom property 

I forgot :( I had added such a property in https://github.com/koreader/crengine/commit/6b8113aaa7d5f4fb60c9777ccc81f596e353e0bf .
Got a book with extra nbsp again, and was looking around in crengine on how to avoid them - while it was already there.

Would adding this new style tweak be fine (wording, etc...) ?
image

**Comment by Frenzie** [comment]
Seems fine to me. A few minor stylistic suggestions:

> A publisher might use non-breaking spaces and hyphens to avoid line breaking between some words, which is not always necessary and may have been added to make reading easier. This can cause large word spacing on some lines.
Ignoring them will only use KOReader's own typography rules for line breaking.

**Comment by poire-z** [comment]
Should it be:
Ignore publisher line break restrictions
or
Ignore publisher line breaking restrictions
?

**Comment by Frenzie** [comment]
I'd go with `Ignore publisher line-break restrictions`
