### PR TITLE
Fix some CSS case sensitivity issues

### LINKED ISSUE #140: Attribute value case shouldn't matter (for the most part)
See https://github.com/koreader/koreader/issues/3459#issuecomment-375909783

[classname-case.xhtml.txt](https://github.com/koreader/crengine/files/1844642/classname-case.xhtml.txt)

```html
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title></title>
  <style>
.borderBottom {
  border-bottom: 0.15em solid;
}
.borderBOTTOM {
  border-bottom: 0.15em SOLID;
}
</style>
</head>

<body>
<p class="borderBottom">Should have border-bottom.</p>
<p class="borderbottom">Should <em>not</em> have border-bottom.</p>
<p class="borderBOTTOM">Should have border-bottom.</p>
</body>
</html>
```

### Expected

screenshot_2018-03-24_18-36-20

### Received

screenshot_2018-03-24_18-36-04

### PR DESCRIPTION
**Pull request by poire-z**
- Case should not matter when parsing CSS declaration properties ("`Font-Weight`"), named values ("`Bold`"), named length ("`LARGER`"), and length units ("`10PX`").
- Case should matter when matching class names ("`<div class="bottomBorder"` should not use CSS defined as "div.bottomborder").
- Fix color rendering of background image (the conversion of internal images from 32bpp to the final 16bpp was simply not implemented).
- Fix existing unwanted lowercasing of background image file reference (`url("BackgrounImage.jpeg")` was lowercased in the process of parsing it.

See discussion in #140. Closes #140.

There is still an existing issue with resolution of relative image path there that could fail (couldn't find a quick fix for this), and some other existing strange issue when no-repeat is used (as in the After screenshot before, that looked the same before, with a lowercase filename and fullpath).

Sample file for testing that kind of stuff: 

[test-css-nocase.epub.zip](https://github.com/koreader/crengine/files/1946521/test-css-nocase.epub.zip)

Before:
<kbd>before</kbd>

After:
<kbd>image</kbd>

### CODE REVIEW

File: crengine/src/lvrend.cpp [hunk 1]
```diff
@@ -2362,15 +2362,18 @@ void DrawBackgroundImage(ldomNode *enode,LVDrawBuf & drawbuf,int x0,int y0,int d
...
             filename.trim();
-            if (filename.lowercase().startsWith("\"")) filename = filename.substr(1);
-            if (filename.lowercase().endsWith("\"")) filename = filename.substr(0, filename.length() - 1);
+            if (filename.startsWith("\"")) filename = filename.substr(1);
+            if (filename.endsWith("\"")) filename = filename.substr(0, filename.length() - 1);
             filename.trim();
-            if (filename.lowercase().startsWith("../")) filename = filename.substr(3);
+            // This is probably wrong: we should have resolved the path at
+            // stylesheet parsing time (but the current code does not).
+            // Here, all files relative path information is no more accessible.
```
Comment (Frenzie) [inline crengine/src/lvrend.cpp]: Huh, I guess they're just not used that much or something?

Comment (poire-z) [reply crengine/src/lvrend.cpp]: Or we just don't notice their absence (I didn't expect them to show up before I found it was supported in the code :)

**Comment by poire-z** [comment]
Btw, I wonder about something while testing.
say we have `background-image: url("../paper.png")` in `/OEBPS/template.css`
say we have `/OEBPS/Text/Chapter1.html` that includes `<style link="../templace.css">`
Where should the relative `../paper.png` resolve from ?
- the templace.css location, so that would give `/paper.png` ?
- or the Chapter1.html location, so that would give `/OEBPS/paper.png`

**Comment by Frenzie** [comment]
The CSS file shouldn't care about where it's called from. If it did it'd be unusable. That's `/paper.png`.

**Comment by poire-z** [comment]
Some timings, with the same book I timed in https://github.com/koreader/crengine/pull/97#issuecomment-369733864.

Before #163:

cache before | load time | render time
---------------- | -------------------------- | ----------------
no cache yet | 24 s | 23s

After #163:

cache before | load time | render time
---------------- | -------------------------- | ----------------
no cache yet | 18 s | 16s

So, getting rid of that `lowercase()` in classname checks, as predicted in https://github.com/koreader/koreader/issues/3459#issuecomment-375909783, gives a good 25%/30% gain !

**Comment by Frenzie** [comment]
Excellent. :-) Timed on PC or Kobo?

**Comment by poire-z** [comment]
On the emulator.
(Same book takes ~145s on my Kobo, so I expect 110s, i'll see when it's bump in a nightly)

**Comment by poire-z** [comment]
145s > 99s on my kobo.
And no problem on arm kobo or android with that endianess worry.
