### PR TITLE
XML parsing: correctly parse CDATA

### LINKED ISSUE #396: Style tag with CDATA doesn't work
Some EPUBs, for example those from Wikisource ([example](https://wsexport.wmflabs.org/book.php?lang=en&format=epub-3&page=Apollonius_of_Tyana_-_The_Pagan_Christ_of_the_Third_Century%2FIntroduction)) have `<style>` elements in the `<head>` of the XHTML files that have [CDATA](https://en.wikipedia.org/wiki/CDATA) in them like this:

```
<style><![CDATA[.class{text-align: foo;}]]></style>
```
None of the contained styling is applied. However changing to simply:
```
<style>.class{text-align: foo;}</style>
```
works fine.

### PR DESCRIPTION
**Pull request by poire-z**
~~Was added in #17, requiring the presence of `type="text/css"`. Just stop requirint it.~~
Closes #396.
~~More correct handling of CDATA should probably be implemented, but well/xml/hell...~~ gentle hell actually, so done:

`<div>abc <![CDATA[d<e&>f]]> ghi</div>` will now add intothe DOM 3 text nodes: `abc  `, `d<e&>f` and ` ghi`, as it's supposed to happen in XML/XHTML.
(In HTML, browsers would not do any specific parsing, with possibly strange results. We do it too in plain HTML.)
More details and discussion at https://github.com/koreader/crengine/issues/396#issuecomment-739245637 and follow up.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/crengine/397)

### CODE REVIEW

File: crengine/src/lvxml.cpp [hunk 1]
```diff
@@ -2989,8 +2989,10 @@ bool LVXMLParser::Parse()
                         m_state = ps_text;
                         break;
                     }
-                    //bypass <![CDATA] in <style type="text/css">
-                    if (PeekCharFromBuffer(1)=='['&&tagname.compare("style")==0&&attrvalue.compare("text/css")==0){
+                    // bypass <![CDATA] in <style type="text/css"> (and more generally in any <style>)
+                    // (We let the trailing ]]> in, our style parser will just ignore it)
+                    // todo: ignoring CDATA should be handled more generally and properly
+                    if ( PeekCharFromBuffer(1)=='[' && tagname.compare("style")==0 ) { // && attrvalue.compare("text/css")==0){
```
Comment (Frenzie) [inline crengine/src/lvxml.cpp:2995]: As I wrote in https://github.com/koreader/crengine/issues/396#issuecomment-737090664 perhaps it should be this instead (but I haven't checked what browsers do to deal with real life documents in the meantime):
```suggestion
                    if ( PeekCharFromBuffer(1)=='[' && tagname.compare("style")==0 ) || attrvalue.compare("text/css")==0) {
```

Comment (poire-z) [reply crengine/src/lvxml.cpp:2995]: Not sure I understand.
What else do you want to catch ? This seems (with some added parens) it would catch `<foo bar="text/css"><[[CDATA...` ?
(tagname is the current tag we're in, and attrvalue is the last attribute value met)

Comment (poire-z) [reply crengine/src/lvxml.cpp:2995]: We would anyway parse any `<style>` or `<style type=blah>` as CSS, if they do not start with `<[[CDATA`.
And previously, if they did, we would just skip content up to the `>` in `P > * {color: blue;}` - which is even more disastrous as the used stylesheet would then be `* {color: blue;}` :/

Comment (Frenzie) [reply crengine/src/lvxml.cpp:2995]: > What else do you want to catch ?

I don't know if I want anything at all, that depends on what browsers do. But per HTML5, only `<style>` and `<style type="text/css">` should be regarded as CSS, while anything else should be discarded as unsupported.

Comment (poire-z) [reply crengine/src/lvxml.cpp:2995]: Well, then that should be handled at a later step, when we check for a `style` tag to parse and apply its text content as a stylesheet. If no type attribute, or type == "text/css": then apply it. If type and type != text/css, just don't parse and don't apply it.
At this early step of XML parsing, we should parse it correctly (which we don't :) and include it in the DOM.

**Comment by poire-z** [comment]
Anyway, having a quick look at XMhelL parsing how hard it would be to handle correctly CDATA.
https://en.wikipedia.org/wiki/CDATA#CDATA_sections_in_XML
https://stackoverflow.com/questions/2784183/what-does-cdata-in-xml-mean

**Review by Frenzie — APPROVED** [review]

File: crengine/src/lvxml.cpp (hunk 1 above)
Comment (Frenzie) [reply crengine/src/lvxml.cpp:2995]: > At this early step of XML parsing

I was missing that part before. It has no place in that. :-)
