### PR TITLE
CSS: adds support for "visibility: hidden", and other fixes

### LINKED ISSUE #418: `transparent` is a valid foreground color as of CSS Colors 3
In CSS Levels 1 and 2, `transparent` was not a "real" colour and could not be used for the foreground color (i.e. `color`). In [CSS Colors 3](https://www.w3.org/TR/css-color-3/#transparent), it's promoted to a real color:

> CSS3 extends the color value to include the ‘transparent’ keyword to allow its use with all properties that accept a <color> value. This simplifies the definition of those properties in CSS3. 

This means that the following:
```html
Before <span style="color:transparent;">transparent</span> After
```
should look like this:
Sigil

In crengine, it has no effect:
Koreader crengine

EPUB with the above:
[transparent-color.epub.zip](https://github.com/koreader/crengine/files/5925299/transparent-color.epub.zip)

### PR DESCRIPTION
**Pull request by poire-z**
#### Text: fix max img height when small line-height

An image having its bottom on the baseline, don't account for the strut added space below when this space would be negative (ie. with line-height: 0, which might be explicitely used to kill that strut added bottom blank space).
See https://github.com/koreader/koreader/issues/7257#issuecomment-774648460. Will allow closing https://github.com/koreader/koreader/issues/7257

#### getRenderedWidths(): fix consecutive non-collapsable spaces

Measured widths could be wrong when other unicode space chars are used, which should not collapse.
Noticed with some MathML book abusing that kind of thing to add spacing:
```html
<mtext>&#8201;</mtext><mtext>&#8201;</mtext><mtext>&#8201;</mtext>
```

#### CSS: adds support for "visibility: hidden"

Will be needed for MathML `<mphantom>`. Feels totally uneeded with eBooks, but I figure it can be nice to have, allowing hiding some content via style tweaks, for example translations in a language learning book...

#### Text: fix some bgcolor issues, handle fgcolor transparent

This sample had rendering issues:
```html
<div style="background-color: red; padding: 1em;">
    More text
    <div style="background-color: yellow; padding: 1em; background-image: url(Lac_sevan_armenie.png)">
        More text2
        <span style="background-color: red;">some red</span>
        and
        <span style="background-color: yellow;">some yellow</span>
        and some transparent
        <span style="color: transparent;">transparent</span>
        and
        <span style="background-color: red; color: transparent;">red</span>
        and
        <span style="background-color: yellow; color: transparent"> yellow</span>
        and done.
    </div>
</div>
```

Before:
image

After (just as Firefox):
image

My previous attempt/hack https://github.com/koreader/crengine/pull/318/commits/05036537bb21d6b52e7a2ece4f852f0fb704a422 seems wrong - don't remember what test case I attempted to solve with it :/
Closes #418 with added support for `color: transparent` (although it doesn't solve the related issue #417).

#### remove global gRootFontSize

Since #413, `lengthToPx()` can access the document and get the root font size. But we need to pass it to lvpagesplitter though.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/crengine/419)

### CODE REVIEW

**Comment by poire-z** [comment]
Do my screenshots looks ugly and blurry above ? They were enlarged when I pasted them... :/
Sorry for that, but couldn't find a way to get them nice as it looks like in KOReader. Got a new laptop at work with a 1920x1080 14' screen, and have to use Windows' own "scaleForDPI", having it at 125% (and Firefox `layout.css.devPixelsPerPx` set to 1.30). Everything is rather a mess... (Outlook inconsistent font sizes...) And now my screenshots here :(

**Review by Frenzie — APPROVED** [review]
lgtm, didn't test but the screenshot speaks of a great improvement either way. ;-)

**Comment by NiLuJe** [comment]
@poire-z: Welcome to the world of HiDPI scaling, where everything is a mess! (Until you hit an easy scale ratio, e.g., 200% ;p).

File: crengine/src/lvtextfm.cpp [hunk 1]
```diff
@@ -4881,8 +4888,12 @@ void LFormattedText::Draw( LVDrawBuf * buf, int x, int y, ldomMarkedRangeList *
                     lUInt32 oldBgColor = buf->GetBackgroundColor();
                     lUInt32 cl = srcline->color;
                     lUInt32 bgcl = srcline->bgcolor;
-                    if ( cl!=0xFFFFFFFF )
-                        buf->SetTextColor( cl );
+                    if ( cl!=0xFFFFFFFF ) {
+                        if ( cl==0xDDFFFFFF ) // color: transparent
```
Comment (NiLuJe) [inline crengine/src/lvtextfm.cpp:4892]: Would it make sense to simply skip everything with zero opacity?

(e.g., `if (cl >> 24U == 0x00)`, and set color: transparent as 0x00000000 above).

(I don't remember if this bit of CRe logic uses alpha or opacity, so this might need to be 0xFF instead of 0x00 ^^.
And/or if the fact that some stuff possibly assumes RGBX instead of alpha/inverted alpha doesn't screw with that idea).

**Comment by Frenzie** [comment]
@NiLuJe 
> (I say welcome, but I don't actually have an HiDPI screen, I just know that it's hilariously bad on most OSes ^^).

It's actually quite a lot better on systems that allegedly don't support it, like Windows XP or good old X11. They do it all and very well, fractional, integers, the whole shebang. (Of course some apps are badly coded and they'll scale the text but not the container, the text but not the icons, etc.) Also they call it DPI and they don't mask it behind percentages.

What they don't support is different DPI *per monitor*.

When you get into "supported" territory in Windows/Wayland, suddenly half your apps are blurry, even though they used to scale *perfectly*.

I don't recall otoh if KOReader interacts nicely with Wayland yet. I'll look into that at some indeterminate point in the future. But the interaction of running KOReader with an X server on Windows — that's an entirely different can of worms. ;)

File: crengine/src/lvtextfm.cpp (hunk 1 above)
Comment (poire-z) [reply crengine/src/lvtextfm.cpp:4892]: Not sure we ever get anything of value above 0x00FFFFFF.

At this point, the foreground color (`cl`, dunno about `bgcl`) can only be 0x00NNNNNN, as it is parsed from #RRGGBB HTML/CSS colors (and we explicitely parse only 6 digits) - and the code that explicitely set black and white color in lvdrawbuf set them to 0x00000000 and 0x00FFFFFF (3 bytes, the upper 4th being 0).
Also, in lvdrawbuf, the `::Draw( int x, int y, const lUInt8 * bitmap...)` that gets the bitmap from FreeType do not seem to do anywhing with the upper byte of this color we have set (unlike what they do with the dest pixel color they are pasting that on to).

So, this 0xFFFFFFFF is just a keyword, a value that can't happen when a color comes from parsing, which means: use the buffer already set color, do not change it - which happens for most book content.
I added another such keyword 0x**DD**FFFFFF that can't happen when color comes from parsing, which means, as the upper byte in hex says "**D**on't **D**raw" :) Just skip it.
I initially went with providing as the foreground color the background color - but that didn't work obviously when the background is an image :)
If you're thinking about explicitely setting a transparent foreground color, this would need LVDrawBuf::Draw() to handle them explicitely to decide to not change the dest pixel - which seems absurd ? (adding code to explictely do nothing when we provide a value we never provided before :)

(But as I don't get much about this alpha stuff, what do I know ? :)

Comment (NiLuJe) [reply crengine/src/lvtextfm.cpp:4892]: Okay, if you're never actually parsing the alpha value from #RGBA quadruples, then that proposal indeed makes no sense ;).

(And the fact that the alpha is sometimes left untouched (i.e., 0) is because of the whole RGBX/inverted alpha shenanigans: it's CRe's way of saying "fully opaque" without actually having to set/handle that byte).

**Review by NiLuJe — APPROVED** [review]

**Comment by poire-z** [comment]
> But the interaction of running KOReader with an X server on Windows — that's an entirely different can of worms. ;)

Somehow, it's not bad with my Xserver from 2007... I found KOReader at the expected size (so, it must be scaled, if it feels the same size/position as on my old laptop), and it looked just like before to me - until you mentionned that :) Looking precisely, it may seems a bit blurry :/ but things on the emulator has never looked as nice as on a device for me - but overall quite ok. So, globally no issue with the KOReader emulator itself.

**Comment by poire-z** [comment]
Work laptop (copied from above):
image

Home laptop, same emulator, new screenshot taken:
image

So, I guess I screenshoted the scaled X11 bitmap - which I then saw scaled again by Firefox when posted on GitHub.... :/
